"""profile_facts

Revision ID: 4b747af609d8
Revises: 2ec708645017
Create Date: 2026-06-03 16:29:54.857051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b747af609d8'
down_revision: Union[str, None] = '2ec708645017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_conversation_id', sa.UUID(), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_profile_facts_category', 'profile_facts', ['category'], unique=False)
    # NOTE: autogenerate wanted to drop ix_chunks_embedding_hnsw (it can't see the
    # op.execute-created HNSW index). Keep it — removed that spurious drop.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_facts_category', table_name='profile_facts')
    op.drop_table('profile_facts')
    # ### end Alembic commands ###
