"""conversations pinned + archived (sidebar)

Revision ID: 68113919ba65
Revises: a1a3e3d1fb0d
Create Date: 2026-06-04 10:29:16.840389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68113919ba65'
down_revision: Union[str, None] = 'a1a3e3d1fb0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: keep ix_chunks_embedding_hnsw — autogenerate can't see the
    # op.execute-created HNSW index; removed its spurious drop.
    op.add_column('conversations', sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('conversations', sa.Column('archived', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'archived')
    op.drop_column('conversations', 'pinned')
    # ### end Alembic commands ###
