"""content_sources + content_chunks (phase5 lecturer)

Revision ID: 96d1d6982add
Revises: 4b747af609d8
Create Date: 2026-06-03 20:51:12.695768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '96d1d6982add'
down_revision: Union[str, None] = '4b747af609d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_sources_created', 'content_sources', ['created_at'], unique=False)
    op.create_table('content_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_chunks_source', 'content_chunks', ['source_id'], unique=False)
    # NOTE: autogenerate wanted to drop ix_chunks_embedding_hnsw (op.execute-created,
    # invisible to model metadata). Keep it — removed that spurious drop.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_chunks_source', table_name='content_chunks')
    op.drop_table('content_chunks')
    op.drop_index('ix_content_sources_created', table_name='content_sources')
    op.drop_table('content_sources')
    # ### end Alembic commands ###
