"""courses table (phase5 lecturer)

Revision ID: a1a3e3d1fb0d
Revises: 96d1d6982add
Create Date: 2026-06-03 21:21:40.856536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1a3e3d1fb0d'
down_revision: Union[str, None] = '96d1d6982add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_courses_source', 'courses', ['source_id'], unique=False)
    # NOTE: keep ix_chunks_embedding_hnsw — autogenerate can't see the
    # op.execute-created HNSW index; removed its spurious drop.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_source', table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
